openapi: 3.0.3
info:
    title: Technical Analysis API
    description: API for managing watchlist and providing strategy insights
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /exchanges:
        get:
            tags:
                - exchange
            summary: list exchange
            operationId: exchange#list
            parameters:
                - name: query
                  in: query
                  description: Optional search query (name or country)
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Optional search query (name or country)
                    example: Provident asperiores qui.
                  example: Est quos est libero hic qui.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Exchange'
                                example:
                                    - acronym: NYSE
                                      city: New York
                                      country: US
                                      display_name: NYSE - New York Stock Exchange (US)
                                      exchange_name: New York Stock Exchange
                                      operating_mic: XNYS
                                    - acronym: NYSE
                                      city: New York
                                      country: US
                                      display_name: NYSE - New York Stock Exchange (US)
                                      exchange_name: New York Stock Exchange
                                      operating_mic: XNYS
                                    - acronym: NYSE
                                      city: New York
                                      country: US
                                      display_name: NYSE - New York Stock Exchange (US)
                                      exchange_name: New York Stock Exchange
                                      operating_mic: XNYS
                                    - acronym: NYSE
                                      city: New York
                                      country: US
                                      display_name: NYSE - New York Stock Exchange (US)
                                      exchange_name: New York Stock Exchange
                                      operating_mic: XNYS
                            example:
                                - acronym: NYSE
                                  city: New York
                                  country: US
                                  display_name: NYSE - New York Stock Exchange (US)
                                  exchange_name: New York Stock Exchange
                                  operating_mic: XNYS
                                - acronym: NYSE
                                  city: New York
                                  country: US
                                  display_name: NYSE - New York Stock Exchange (US)
                                  exchange_name: New York Stock Exchange
                                  operating_mic: XNYS
                                - acronym: NYSE
                                  city: New York
                                  country: US
                                  display_name: NYSE - New York Stock Exchange (US)
                                  exchange_name: New York Stock Exchange
                                  operating_mic: XNYS
    /exchanges/{operating_mic}:
        get:
            tags:
                - exchange
            summary: get exchange
            operationId: exchange#get
            parameters:
                - name: operating_mic
                  in: path
                  description: Operating MIC of the exchange
                  required: true
                  schema:
                    type: string
                    description: Operating MIC of the exchange
                    example: Consectetur consectetur ad corporis a.
                  example: Consectetur corrupti.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Exchange'
                            example:
                                acronym: NYSE
                                city: New York
                                country: US
                                display_name: NYSE - New York Stock Exchange (US)
                                exchange_name: New York Stock Exchange
                                operating_mic: XNYS
    /insights:
        get:
            tags:
                - insights
            summary: list insights
            operationId: insights#list
            parameters:
                - name: X-User-ID
                  in: header
                  description: User ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: User ID
                    example: Fuga temporibus dignissimos necessitatibus excepturi dolores quas.
                  example: Et qui ipsam eos quaerat.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Insight'
                                example:
                                    - action: Id dolores odio fugiat nihil eos.
                                      sentiment: neutral
                                      summary: Repellat quod quo delectus.
                                      symbol: Maiores et.
                                    - action: Id dolores odio fugiat nihil eos.
                                      sentiment: neutral
                                      summary: Repellat quod quo delectus.
                                      symbol: Maiores et.
                            example:
                                - action: Id dolores odio fugiat nihil eos.
                                  sentiment: neutral
                                  summary: Repellat quod quo delectus.
                                  symbol: Maiores et.
                                - action: Id dolores odio fugiat nihil eos.
                                  sentiment: neutral
                                  summary: Repellat quod quo delectus.
                                  symbol: Maiores et.
                                - action: Id dolores odio fugiat nihil eos.
                                  sentiment: neutral
                                  summary: Repellat quod quo delectus.
                                  symbol: Maiores et.
    /watchlist:
        get:
            tags:
                - watchlist
            summary: list watchlist
            operationId: watchlist#list
            parameters:
                - name: X-User-ID
                  in: header
                  description: User ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: User ID
                    example: Explicabo iusto est reiciendis at aut.
                  example: Rem est iure.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/TickerItem'
                                example:
                                    - created_at: "2023-10-27T10:00:00Z"
                                      on_hand: true
                                      symbol: AAPL
                                    - created_at: "2023-10-27T10:00:00Z"
                                      on_hand: true
                                      symbol: AAPL
                            example:
                                - created_at: "2023-10-27T10:00:00Z"
                                  on_hand: true
                                  symbol: AAPL
                                - created_at: "2023-10-27T10:00:00Z"
                                  on_hand: true
                                  symbol: AAPL
                                - created_at: "2023-10-27T10:00:00Z"
                                  on_hand: true
                                  symbol: AAPL
                                - created_at: "2023-10-27T10:00:00Z"
                                  on_hand: true
                                  symbol: AAPL
        post:
            tags:
                - watchlist
            summary: add watchlist
            operationId: watchlist#add
            parameters:
                - name: X-User-ID
                  in: header
                  description: User ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: User ID
                    example: Error vero.
                  example: Eius repellat facilis.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRequestBody'
                        example:
                            on_hand: false
                            symbol: Minima veniam labore tempora sit.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TickerItem'
                            example:
                                created_at: "2023-10-27T10:00:00Z"
                                on_hand: true
                                symbol: AAPL
    /watchlist/{symbol}:
        delete:
            tags:
                - watchlist
            summary: remove watchlist
            operationId: watchlist#remove
            parameters:
                - name: symbol
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Cumque dolor.
                  example: Voluptates repudiandae doloremque eveniet.
                - name: X-User-ID
                  in: header
                  description: User ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: User ID
                    example: Rem minima eaque mollitia iure ab.
                  example: Nisi esse temporibus reiciendis aut ut.
            responses:
                "204":
                    description: No Content response.
components:
    schemas:
        AddRequestBody:
            type: object
            properties:
                on_hand:
                    type: boolean
                    example: false
                symbol:
                    type: string
                    example: Eum veniam praesentium iure id.
            example:
                on_hand: true
                symbol: Iste commodi impedit.
            required:
                - symbol
                - on_hand
        Exchange:
            type: object
            properties:
                acronym:
                    type: string
                    description: Short identifier
                    example: NYSE
                city:
                    type: string
                    description: City location
                    example: New York
                country:
                    type: string
                    description: ISO 3166 alpha-2 country code
                    example: US
                    minLength: 2
                    maxLength: 2
                display_name:
                    type: string
                    description: Formatted name for UI
                    example: NYSE - New York Stock Exchange (US)
                exchange_name:
                    type: string
                    description: Full descriptive name
                    example: New York Stock Exchange
                operating_mic:
                    type: string
                    description: 4-character ISO 10383 code
                    example: XNYS
                    minLength: 4
                    maxLength: 4
            description: A financial market or institution
            example:
                acronym: NYSE
                city: New York
                country: US
                display_name: NYSE - New York Stock Exchange (US)
                exchange_name: New York Stock Exchange
                operating_mic: XNYS
            required:
                - operating_mic
                - exchange_name
                - display_name
                - country
                - city
        Insight:
            type: object
            properties:
                action:
                    type: string
                    description: Recommended Action
                    example: Excepturi repudiandae.
                sentiment:
                    type: string
                    description: Market Sentiment
                    example: neutral
                    enum:
                        - bullish
                        - bearish
                        - neutral
                summary:
                    type: string
                    description: Analysis Summary
                    example: Quo repellat voluptate reprehenderit.
                symbol:
                    type: string
                    description: Stock Symbol
                    example: Nobis atque iste ut.
            example:
                action: Cum et voluptates debitis laborum.
                sentiment: bearish
                summary: Facere velit perspiciatis amet quas.
                symbol: Cumque voluptatem beatae.
            required:
                - symbol
                - sentiment
                - summary
                - action
        TickerItem:
            type: object
            properties:
                created_at:
                    type: string
                    description: Creation timestamp
                    example: "2023-10-27T10:00:00Z"
                    format: date-time
                on_hand:
                    type: boolean
                    description: Whether user holds the stock
                    example: true
                symbol:
                    type: string
                    description: Stock Symbol
                    example: AAPL
            example:
                created_at: "2023-10-27T10:00:00Z"
                on_hand: true
                symbol: AAPL
            required:
                - symbol
                - on_hand
tags:
    - name: watchlist
      description: Manage user watchlist
    - name: insights
      description: Provide AI insights
    - name: exchange
      description: Manage financial exchanges
